foodmenu_app/app/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='app'
urlpatterns = [
    path('', views.index,name='index'),
    path("<int:id>/",views.detail,name='detail'),
    path("add/",views.create_item,name='Item_name'),
    path("update/<int:id>/",views.update,name="update")
]

foodmenu_app/foodmenu_app/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
]

foodmenu_app/app/models.py
from django.db import models

class Item(models.Model):
    def __str__(self):
        return f"{self.Item_Name}"
        
        
    Item_Name = models.CharField(max_length=200)
    Item_desc = models.CharField(max_length=200)
    Item_price = models.IntegerField()
    Item_image=models.CharField(max_length=500,default="https://th.bing.com/th/id/OIP.NULWEmlj4g8ASx3w_Ps7MQAAAA?w=155&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3")
   

foodmenu_app/app/forms.py
from django import forms
from .models import Item
class Itemform(forms.ModelForm):
    class Meta:
        model=Item
        fields = ['Item_Name','Item_desc','Item_price','Item_image']

foodmenu_app/app/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .forms import Itemform
from .models import Item
def index(request):
    item_list=Item.objects.all()
    context={"item_list":item_list}
    return render(request,"app/index.html",context)
def detail(request,id):
    list1=Item.objects.get(id=id)
    context={"list1":list1}
    return render(request,"app/list.html",context)
def create_item(request):
    form=Itemform(request.POST or None)
    if request.method=='POST':
        if form.is_valid():
            form.save()
            return redirect("app:index")
    context={'form':form}
    return render(request,"app/form_add.html",context)

def  update(request,id):
    lists=Item.objects.get(id=id)
    form=Itemform(request.POST or None,instance=lists)
    if request.method == "POST":
     if form.is_valid():
        form.save()
        return redirect("app:index")
    context={"form":form}
    return render(request,"app/form_add.html",context)

foodmenu_app/app/templates/app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <title>Document</title>
</head>
<body>
    <nav class="bg-blue-600 text-white">
     <div class="flex justify-between px-4 py-4">
      <a href="" class="font-bold text-3xl">FoodApp</a>
      <div class="space-x-6">
        <a href="">Contact</a>
        <a href="">Address</a>
        <a href="">About us</a>
      </div>
     </div>
   </nav>
    {% block body %}
    {% endblock %}
</body>
</html>

foodmenu_app/app/templates/app/form_add.html
{% extends 'app/base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Save</button>
</form>
{% endblock %}

foodmenu_app/app/templates/app/index.html
{% extends 'app/base.html' %}
{% block body %}
<div class="container mx-auto p-6 space-y-6">
  {% for item in item_list %}
  <div class="flex flex-col md:flex-row items-start bg-sky-200 rounded-lg shadow-md overflow-hidden space-y-4">
      <div class="md:w-1/3 px-3">
        <img src="{{item.Item_image}}"  alt="{{ item.Item_Name }}" class="w-full h-60 mb-2 rounded-lg">
      </div>
      <div class="mx-10 bg-sky-200 justify-between">
         <h3 class="font-bold text-2xl">{{ item.Item_Name }}</h3>
          <p class="font-semibold">{{ item.Item_desc }}</p>
          <h3 class=" text-2xl font-bold text-green-900">₹{{ item.Item_price }}</h3>
      </div>
      <div class="mt-4">
        <a href="{% url 'app:detail' item.id %}" class=" text-3xl font-bold hover:text-green-900 transistion">Detail</a>
      </div>
  </div>
  {% endfor %}
</div>

   {% endblock %}

foodmenu_app/app/templates/app/list.html
{% extends 'app/base.html' %}
{% block body%}
<div class="flex mx-10 overflow-hidden mt-10">
  <div>
      <img src="{{list1.Item_image}}" alt="image.Image_Name" class="w-128 rounded-lg">
  </div>
  <div class="mx-10">
     <div><h2>{{ list1.Item_Name}}</h2></div>
     <div><p2 class="text-1xl">{{ list1.Item_desc}}</p2></div>
     <div><h2 class="font-bold text-3xl">₹{{ list1.Item_price}}</h2></div>
     <div class="mt-5 space-x-5">
        <a href="{% url 'app:update' list1.id%}" class=" text-2xl font-bold bg-yellow-400 px-5 rounded-lg">Edit</a>
        <a href="" class="font-bold text-2xl bg-red-300 rounded-lg px-5">Delete</a></div>
     
  </div>
</div>
{% endblock %}